# Generated by Django 4.2.7 on 2023-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_parol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lavozim',
            field=models.CharField(choices=[('admin', 'Admin'), ('azo', 'Azo')], max_length=100),
        ),
    ]
