# Generated by Django 4.2.7 on 2023-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_davomat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='davomat',
            old_name='user',
            new_name='familya',
        ),
        migrations.AddField(
            model_name='davomat',
            name='ism',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='davomat',
            name='user_id',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
