# Generated by Django 4.2.7 on 2023-12-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_davomat_familya_davomat_ism_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='bor',
        ),
        migrations.AlterField(
            model_name='davomat',
            name='sana',
            field=models.CharField(max_length=100),
        ),
    ]
