# Generated by Django 4.2.7 on 2023-12-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_davomat_bor_alter_davomat_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='aktiv',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='davomat',
            name='sana',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
