# Generated by Django 4.2.7 on 2023-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistika',
            name='qatnashmagan',
            field=models.IntegerField(default=0),
        ),
    ]
