# Generated by Django 4.2.7 on 2023-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0002_statistika_qatnashmagan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elon',
            name='ovoz',
        ),
        migrations.AddField(
            model_name='elon',
            name='tugash',
            field=models.BooleanField(default=False),
        ),
    ]
