# Generated by Django 4.2.7 on 2023-12-13 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ovoz', '0005_remove_taklif_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baxo',
            old_name='elon',
            new_name='taklif_id',
        ),
        migrations.AddField(
            model_name='baxo',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
