# Generated by Django 4.2.7 on 2023-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0007_remove_baxo_baza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baxo',
            name='taklif_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='baxo',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
