# Generated by Django 4.2.7 on 2023-12-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0008_alter_baxo_taklif_id_alter_baxo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistika',
            name='elon',
        ),
        migrations.AddField(
            model_name='statistika',
            name='taklif_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
