# Generated by Django 4.2.7 on 2023-12-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0010_rename_betaraf_statistika_betaraflar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='statistika/'),
        ),
    ]
