# Generated by Django 4.2.7 on 2023-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0012_remove_statistika_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistika',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistika',
            name='nomzod',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
