# Generated by Django 4.2.7 on 2023-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0013_statistika_name_statistika_nomzod'),
    ]

    operations = [
        migrations.AddField(
            model_name='taklif',
            name='xal',
            field=models.BooleanField(default=False),
        ),
    ]
