# Generated by Django 4.2.7 on 2023-12-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0014_taklif_xal'),
    ]

    operations = [
        migrations.AddField(
            model_name='baxo',
            name='xal',
            field=models.BooleanField(default=False),
        ),
    ]
