# Generated by Django 4.2.7 on 2023-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoz', '0015_baxo_xal'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistika',
            name='xal',
            field=models.BooleanField(default=False),
        ),
    ]
